// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class ${className} {
  ${className}._();

  <#list fieldList as field>
  static const String ${field.name} = '${field.value}';
  </#list>
}
